### PR TITLE
Fix random bot remove with whitespaces on name

### PR DESCRIPTION
**Pull request by TriForceX**

### CODE REVIEW

**Comment by Daggolin** [comment]
Your pull request doesn't really make clear how you encountered the issue you're trying to fix and how you tested whether everything is working as intended or not. Even for seemingly small pull requests it may be a good idea to provide some description.

It looks to me as if you encountered a bug that prevents the server from automatically kicking bots due to unexpected netnames when trying to enforce bot_minplayers. In your case the reason for the game module failing to kick a random bot was the presence of whitespace characters in their netname. Unfortunately that doesn't seem to be the only issue with the existing code. Looking at the code G_RemoveRandomBot is using a 36 byte char array to store the clean name of the bot and as MAX_NETNAME is defined as 36 as well this can lead to names with up to 35 characters getting passed as command argument into the engine. The engine however only stores names in a 32 byte char array, so trying to kick a target with a name longer than 31 characters should still not work properly.

Looking past mvsdk there is a couple of forks that seem to have increased their MAX_NETNAME value far beyond the default value of 36, making these kicks by netname even less reliable on there.

And to make things even worse: as players and bots can use the same netname the system may even end up kicking real players rather than bots due to netname collisions if the client number of a player is lower than the client number of the bot that's supposed to be kicked.

As the above clearly shows it's generally not a good idea to use netnames for such automated kicks, especially not when the client number is available right there. So rather than working around a single issue it would be far better to either EXEC_INSERT a "clientkick" for the client number or to call trap_DropClient on the bot. The clientkick command in the engine calls DropClient on the target and updates the lastPacketTime for the client to handle switching from CS_ZOMBIE to CS_FREE later. The call to trap_DropClient does NOT update the lastPacketTime. I am not sure if we need the lastPacketTime to update when kicking a bot here, but that's something one should take a closer look at before making a decision.

So I see 3 options to handle kicking random bots:
    - inserting a "clientkick" command
    - calling trap_DropClient
    - calling trap_BotGetServerCommand to update the lastPacketTime and then calling trap_DropClient

I am going to look into which of those options would be best sometime later, but I am rejecting this pull request now, as it's just a partial workaround for a bigger problem.

Thanks for reporting this issue, I am going to take care of it!

**Comment by aufau** [comment]
I would merge the pr, it's better than it was before. There may be another bug (netname too long) but it's a separate issue and who knows when it will be fixed. Fixing it on top of this wouldn't hurt neither.

But as @Daggolin said, if there were detailed steps to reproduce the issue, showing that a specific error is fixed after this commit, I think it wouldn't be easy to reject such patch.

**Comment by TriForceX** [comment]
I thought the title was clear, also the code says where the problem is (on RemoveRandomBot used by CheckMinimumPlayers)... anyways, yes, the game cant use "kick" on bots which has a custom name with whitespaces on it (if bot_minplayers is enabled).

I dont understand why this got rejected, a "fix" is different than an "improvement"... of couse many things can be "improved" or changed to be better, but the current pull-request is related with the current code, and the current code is supposed to work with custom bot names (altname/funname). an "this can be improved" should not be a reason yo reject a "fix this in the meantime" in the current code.

**Comment by aufau** [comment]
Maybe title is clear to someone who took a peek into the code like @Daggolin did, but to me it doesn't say anything really. Looking at the commit I get idea what type of a bug it is, but to reproduce it I'd need to read code around and figure it out myself.

**Comment by TriForceX** [comment]
Yea of course, thats why i said "i thought it was clear"... it was a mistake to assume that, i should be more specific the next time.

Anyways thats not a reason to reject a simple pull-request, even if it can be changed to be improved later. I think a "fix" should be considered when are for current stuff. I agree that can be improved, but for the meantime, things like this should be considered... It is common that there are things that, when delving deeper, one realizes that them can be changed and improved ... but that is in the medium/long time.

**Comment by LordAttano** [comment]
> Anyways thats not a reason to reject a simple pull-request, even if it can be changed to be improved later. I think a "fix" should be considered when are for current stuff. I agree that can be improved, but for the meantime, things like this should be considered... It is common that there are things that, when delving deeper, one realizes that them can be changed and improved ... but those things are generally for the medium / long term.

A slight improvement is by no means a _fix_ for the issue. When your _fix_ is only a partial and _temporary_ workaround, and would need to be replaced by a _proper_ fix, which is not even a complicated one to my knowledge, I _do_ understand why Daggo declined your pull request. He even explained in great detail _why_ he declined it, but thanked you for pointing out the issue, and said he would look into writing a fix for it. Either have patience for Daggo to commit his fix, which he most likely already finished, or come up with a better one yourself with the notes he gave you taken into account.

**Comment by Daggolin** [comment]
I didn't expect to spark such a debate. When I read the function I noticed that it had serveral other issues that required fixing and concluded it should use client numbers rather than netnames. As I explained earlier kicking by client number could be done either by inserting a `clientkick` command or by calling `trap_DropClient` directly. Knowing that inserting commands generally is something one should avoid I decided to take a quick look at the engine kick commands to see if they do anything besides just dropping the client. As they also updated a time value I concluded someone should take a closer look at it and posted my findings here. I realize that ending the comment with "I am going to take care of it" isn't very inviting, but I wouldn't have mind if the commit in the pull request would've been updated with an improved version and a clear/detailed description of everything taken into consideration.

There is however no point in arguing to accept a _partial_ and _temporary_ workaround a few days before a proper fix, when the workaround doesn't contribute anything a proper fix could base on. I think @LordAttano explained it very well.

Anyway you can find a fix in the Daggolin/mvsdk repository. I am intending to merge it into mvdevs/mvsdk along with a couple of other things after reviewing some of the other things again. The commit message is very detailed to explain why I decided to do things the way I did. It should also help to understand why I decided for another solution than ioq3, DS-Online, etc. did.

**Pull request closed without merging**
